const veeps = [
  'John Adams',
  'Thomas Jefferson',
  'Aaron Burr',
  'George Clinton',
  'Elbridge Gerry',
  'Daniel D. Tompkins',
  'John C. Calhoun',
  'Martin Van Buren',
  'Richard M. Johnson',
  'John Tyler',
  'George M. Dallas',
  'Millard Fillmore',
  'William R. King',
  'John C. Breckinridge',
  'Hannibal Hamlin',
  'Andrew Johnson',
  'Schuyler Colfax',
  'Henry Wilson',
  'William A. Wheeler',
  'Chester A. Arthur',
  'Thomas A. Hendricks',
  'Levi P. Morton',
  'Adlai Stevenson',
  'Garret A. Hobart',
  'Theodore Roosevelt',
  'Charles W. Fairbanks',
  'James S. Sherman',
  'Thomas R. Marshall',
  'Calvin Coolidge',
  'Charles G. Dawes',
  'Charles Curtis',
  'John Nance Garner',
  'Henry A. Wallace',
  'Harry S. Truman',
  'Alben W. Barkley',
  'Richard M. Nixon',
  'Lyndon B. Johnson',
  'Hubert H. Humphrey',
  'Spiro Agnew',
  'Gerald R. Ford',
  'Nelson A. Rockefeller',
  'Walter F. Mondale',
  'George H. W. Bush',
  'Dan Quayle',
  'Al Gore',
  'Dick Cheney',
  'Joe Biden',
  'Mike Pence',
  'Kamala Harris',
  'JD Vance',
];
